name: cdk deploy

on:
  pull_request:
    types: [closed]
    branches: [master, develop]
jobs:
  aws_cdk:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'

      - name: Setup dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: CDK Deploy prod
        if: github.ref == 'master' && github.event.pull_request.merged == true
        run: yarn deploy:prod
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy dev
        if: github.ref == 'develop' && github.event.pull_request.merged == true
        run: yarn deploy:dev
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
